export type SourceKind = "retailer" | "marketplace" | "classifieds" | "delivery_aggregator";
export type SourcePlan = "pilot" | "candidate" | "excluded";

export interface Source {
  id: string;
  name: string;
  url: string;
  kind: SourceKind;
  categories: string[];
  plan: SourcePlan;
  samples?: string[];
  note?: string;
}

export const SOURCES: Source[] = [
  {
    id: "birmarket",
    name: "Birmarket (Umico)",
    url: "https://birmarket.az/",
    kind: "marketplace",
    categories: ["elektronika", "parfüm", "kosmetika", "məişət", "geyim", "uşaq"],
    plan: "pilot",
    samples: [
      "https://birmarket.az/tags/dior-sauvage",
      "https://birmarket.az/product/396858-tualet-suyu-dior-sauvage-100-ml",
    ],
    note: "Bir məhsul üzrə bir neçə satıcı. Ad ilə link uyğun gəlmir, adı əsas götür.",
  },
  {
    id: "kontakt",
    name: "Kontakt Home",
    url: "https://kontakt.az/",
    kind: "retailer",
    categories: ["elektronika", "məişət texnikası", "ətriyyat", "mebel"],
    plan: "pilot",
    samples: ["https://kontakt.az/iphone-15-128-gb-black"],
    note: "Qiymət başlıq meta-sında (product:price:amount).",
  },
  {
    id: "irshad",
    name: "İrşad Electronics",
    url: "https://irshad.az/",
    kind: "retailer",
    categories: ["elektronika", "məişət texnikası", "mebel"],
    plan: "pilot",
    samples: ["https://irshad.az/mehsullar/iphone-15-128-gb-black"],
    note: "Qiymət və köhnə qiymət səhifə mətnindədir.",
  },
  {
    id: "bakuelectronics",
    name: "Baku Electronics",
    url: "https://bakuelectronics.az/",
    kind: "retailer",
    categories: ["elektronika"],
    plan: "candidate",
  },
  {
    id: "ispace",
    name: "iSpace",
    url: "https://ispace.az/",
    kind: "retailer",
    categories: ["elektronika"],
    plan: "candidate",
  },
  {
    id: "almali",
    name: "Almalı",
    url: "https://almali.az/",
    kind: "retailer",
    categories: ["elektronika"],
    plan: "candidate",
    samples: ["https://almali.az/product/iphone-15-128gb-black/"],
  },
  {
    id: "breezy",
    name: "Breezy",
    url: "https://breezy.az/",
    kind: "retailer",
    categories: ["elektronika"],
    plan: "candidate",
    samples: ["https://breezy.az/smartphone/vendor=apple/series=iphone-15/internal-memory-size=128-gb"],
  },
  {
    id: "bazarstore",
    name: "Bazarstore",
    url: "https://bazarstore.az/",
    kind: "retailer",
    categories: ["ərzaq", "məişət kimyası", "gigiyena"],
    plan: "candidate",
  },
  {
    id: "arazmarket",
    name: "Araz Market",
    url: "https://www.arazmarket.az/",
    kind: "retailer",
    categories: ["ərzaq", "məişət kimyası", "gigiyena"],
    plan: "candidate",
  },
  {
    id: "bravo",
    name: "Bravo Supermarket",
    url: "https://bravosupermarket.az/",
    kind: "retailer",
    categories: ["ərzaq", "məişət kimyası", "gigiyena"],
    plan: "candidate",
  },
  {
    id: "neptun",
    name: "Neptun",
    url: "https://neptun.az/",
    kind: "retailer",
    categories: ["ərzaq", "məişət kimyası", "gigiyena"],
    plan: "candidate",
  },
  {
    id: "omid",
    name: "Omid",
    url: "https://omid.az/",
    kind: "retailer",
    categories: ["kosmetika", "gigiyena", "məişət kimyası"],
    plan: "candidate",
    samples: ["https://omid.az/collections/yeni-gelen-mehsullar"],
  },
  {
    id: "yvesrocher",
    name: "Yves Rocher AZ",
    url: "https://www.yvesrocher.az/",
    kind: "retailer",
    categories: ["kosmetika", "gigiyena", "parfüm"],
    plan: "candidate",
    samples: ["https://www.yvesrocher.az/az/products/80049"],
  },
  {
    id: "kosmetika",
    name: "Kosmetika.az",
    url: "https://kosmetika.az/",
    kind: "retailer",
    categories: ["kosmetika"],
    plan: "candidate",
    note: "Domen kataloq məlumatına əsaslanır, yoxlanmalıdır.",
  },
  {
    id: "aromi",
    name: "Aromi",
    url: "https://aromi.az/",
    kind: "retailer",
    categories: ["parfüm"],
    plan: "candidate",
    samples: ["https://aromi.az/kisi-ucun-etir/christian-dior-sauvage/"],
  },
  {
    id: "parfumshop",
    name: "ParfumShop",
    url: "https://www.parfumshop.az/",
    kind: "retailer",
    categories: ["parfüm"],
    plan: "candidate",
    samples: ["https://www.parfumshop.az/index.php?route=product/product&product_id=7076"],
  },
  {
    id: "lalafo",
    name: "Lalafo",
    url: "https://lalafo.az/",
    kind: "classifieds",
    categories: ["hər sahə"],
    plan: "candidate",
    samples: [
      "https://lalafo.az/azerbaijan/krasota-i-zdorove/parfyumeriya-2/q-dior-sauvage-100ml-qiymeti",
      "https://lalafo.az/digyakh/ads/kosmetik-dst-3-mhsul-id-110606107",
    ],
    note: "Fərdi satıcılar. Elan tarixi səhifədə var. Şəxsi məlumat toplanmır.",
  },
  {
    id: "tapaz",
    name: "Tap.az",
    url: "https://tap.az/",
    kind: "classifieds",
    categories: ["hər sahə"],
    plan: "candidate",
    samples: ["https://tap.az/elanlar?keywords=dior+sauvage"],
    note: "Fərdi satıcılar. Şəxsi məlumat toplanmır.",
  },
  {
    id: "maqazin",
    name: "Maqazin.az",
    url: "https://maqazin.az/",
    kind: "classifieds",
    categories: ["hər sahə"],
    plan: "candidate",
    samples: ["https://maqazin.az/dior-sauvage-30-ml-etri-117471.html"],
  },
  {
    id: "wolt",
    name: "Wolt Azərbaycan",
    url: "https://wolt.com/az/aze",
    kind: "delivery_aggregator",
    categories: ["ərzaq", "aptek", "kosmetika"],
    plan: "excluded",
    note: "Restoran, market və apteklərin qiymətləri var. Xarici platformadır, istifadə şərtləri yoxlanmadan toxunulmur.",
  },
];
